"use client";

import PageHeader from "@/components/shared/PageHeader";
import { FolderGit2, Star, GitFork, ExternalLink, RefreshCw } from "lucide-react";
import Link from "next/link";

const mockProjects = [
  { id: 1, title: "task-manager-api", desc: "A robust REST API for task management built with Node.js, Express, and PostgreSQL.", tech: ["Node.js", "Express", "PostgreSQL"], stars: 12, forks: 4, synced: "2h ago", url: "#" },
  { id: 2, title: "react-weather-dashboard", desc: "Real-time weather tracking dashboard utilizing OpenWeather API and React Query.", tech: ["React", "TypeScript", "Tailwind"], stars: 34, forks: 8, synced: "1d ago", url: "#" },
  { id: 3, title: "se-os-portfolio", desc: "My personal developer portfolio generated by SE-OS.", tech: ["Next.js", "Framer Motion"], stars: 5, forks: 0, synced: "Just now", url: "#" },
];

export default function ProjectsPage() {
  return (
    <div className="space-y-8 pb-12">
      <PageHeader 
        title="Portfolio Projects" 
        subtitle="Manage and showcase your best work. Sync directly from GitHub."
        action={
          <button className="px-4 py-2 bg-primary text-primary-foreground rounded-lg font-medium hover:bg-primary/90 flex items-center gap-2">
            <RefreshCw className="w-4 h-4" /> Sync GitHub
          </button>
        }
      />

      <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-3">
        {mockProjects.map(project => (
          <div key={project.id} className="bg-card border rounded-xl overflow-hidden shadow-sm flex flex-col hover:border-primary/50 transition-colors group">
            <div className="p-6 flex-1 flex flex-col">
              <div className="flex items-start justify-between mb-3">
                <div className="flex items-center gap-2 text-primary">
                  <FolderGit2 className="w-5 h-5" />
                  <h3 className="font-bold text-lg text-foreground group-hover:text-primary transition-colors">{project.title}</h3>
                </div>
                <Link href={project.url} className="text-muted-foreground hover:text-foreground">
                  <ExternalLink className="w-4 h-4" />
                </Link>
              </div>
              <p className="text-sm text-muted-foreground flex-1 mb-4 line-clamp-3">
                {project.desc}
              </p>
              <div className="flex flex-wrap gap-2 mb-4">
                {project.tech.map(t => (
                  <span key={t} className="px-2 py-1 bg-muted rounded text-xs font-medium text-muted-foreground">
                    {t}
                  </span>
                ))}
              </div>
            </div>
            <div className="bg-muted/30 px-6 py-3 border-t flex items-center justify-between text-xs text-muted-foreground font-medium">
              <div className="flex gap-4">
                <span className="flex items-center gap-1.5 hover:text-yellow-500 transition-colors"><Star className="w-3.5 h-3.5" /> {project.stars}</span>
                <span className="flex items-center gap-1.5 hover:text-foreground transition-colors"><GitFork className="w-3.5 h-3.5" /> {project.forks}</span>
              </div>
              <span>Synced {project.synced}</span>
            </div>
          </div>
        ))}

        {/* Add New Project Card */}
        <button className="bg-muted/10 border-2 border-dashed rounded-xl flex flex-col items-center justify-center p-6 text-muted-foreground hover:bg-muted/30 hover:text-foreground transition-colors min-h-[250px] gap-3">
          <div className="w-12 h-12 rounded-full bg-muted flex items-center justify-center">
            <FolderGit2 className="w-5 h-5" />
          </div>
          <div className="text-center">
            <h3 className="font-medium text-foreground">Add Manual Project</h3>
            <p className="text-sm mt-1">Create a project without linking a repository.</p>
          </div>
        </button>
      </div>
    </div>
  );
}
