"""initial schema

Revision ID: 3f28267f5824
Revises: 
Create Date: 2026-10-03 16:57:33.197127

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3f28267f5824'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('coding_problems',
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('topic', sa.Enum('ARRAYS', 'STRINGS', 'LINKED_LISTS', 'TREES', 'GRAPHS', 'DYNAMIC_PROGRAMMING', name='topic'), nullable=False),
    sa.Column('company_tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('examples', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('constraints', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('starter_code', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('solution_code', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('test_cases', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('source_url', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('github_id', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('USER', 'MENTOR', 'ADMIN', name='role'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('github_id'),
    sa.UniqueConstraint('google_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('career_goals',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal_type', sa.Enum('BACKEND', 'FRONTEND', 'FULLSTACK', 'AI_ML', 'DEVOPS', 'CLOUD', 'SECURITY', 'DATA', name='goaltype'), nullable=False),
    sa.Column('target_role', sa.String(length=255), nullable=False),
    sa.Column('target_company', sa.String(length=255), nullable=True),
    sa.Column('timeline_months', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_plans',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('tasks', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('completion_rate', sa.Float(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('github_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('access_token_encrypted', sa.Text(), nullable=True),
    sa.Column('public_repos', sa.Integer(), nullable=False),
    sa.Column('followers', sa.Integer(), nullable=False),
    sa.Column('following', sa.Integer(), nullable=False),
    sa.Column('contributions_this_year', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('interview_prep',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('question', sa.Text(), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('difficulty', sa.String(length=50), nullable=False),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('last_reviewed', sa.DateTime(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('interview_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('problem_title', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty'), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('code_snapshot', sa.Text(), nullable=True),
    sa.Column('video_url', sa.String(length=1024), nullable=True),
    sa.Column('audio_transcript', sa.Text(), nullable=True),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('ended_at', sa.DateTime(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'SUBMITTED', 'ASSESSED', name='sessionstatus'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('job_applications',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('company_name', sa.String(length=255), nullable=False),
    sa.Column('role_title', sa.String(length=255), nullable=False),
    sa.Column('job_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.Enum('SAVED', 'APPLIED', 'PHONE_SCREEN', 'TECHNICAL', 'ONSITE', 'OFFER', 'REJECTED', 'WITHDRAWN', name='jobstatus'), nullable=False),
    sa.Column('applied_at', sa.DateTime(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('salary_min', sa.Float(), nullable=True),
    sa.Column('salary_max', sa.Float(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leetcode_stats',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=255), nullable=False),
    sa.Column('easy_solved', sa.Integer(), nullable=False),
    sa.Column('medium_solved', sa.Integer(), nullable=False),
    sa.Column('hard_solved', sa.Integer(), nullable=False),
    sa.Column('total_solved', sa.Integer(), nullable=False),
    sa.Column('streak', sa.Integer(), nullable=False),
    sa.Column('last_synced', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('portfolio_projects',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('tech_stack', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('github_url', sa.String(length=1024), nullable=True),
    sa.Column('live_url', sa.String(length=1024), nullable=True),
    sa.Column('thumbnail_url', sa.String(length=1024), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('practice_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('problem_id', sa.UUID(), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('passed_tests', sa.Integer(), nullable=False),
    sa.Column('total_tests', sa.Integer(), nullable=False),
    sa.Column('time_ms', sa.Integer(), nullable=False),
    sa.Column('memory_mb', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('submitted_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['problem_id'], ['coding_problems.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('token_hash', sa.String(length=512), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('resumes',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('personal_info', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('experience', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('education', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('projects', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('certifications', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preferences',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_email', sa.Boolean(), nullable=False),
    sa.Column('notification_push', sa.Boolean(), nullable=False),
    sa.Column('study_reminder_time', sa.String(length=5), nullable=True),
    sa.Column('theme', sa.String(length=50), nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('user_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('avatar_url', sa.String(length=1024), nullable=True),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('github_username', sa.String(length=255), nullable=True),
    sa.Column('linkedin_url', sa.String(length=1024), nullable=True),
    sa.Column('career_goal', sa.String(length=255), nullable=True),
    sa.Column('current_level', sa.Enum('BEGINNER', 'INTERMEDIATE', 'ADVANCED', name='currentlevel'), nullable=True),
    sa.Column('years_experience', sa.Float(), nullable=True),
    sa.Column('daily_study_hours', sa.Float(), nullable=True),
    sa.Column('onboarding_completed', sa.Boolean(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('interview_assessments',
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('overall_score', sa.Float(), nullable=False),
    sa.Column('code_score', sa.Float(), nullable=False),
    sa.Column('communication_score', sa.Float(), nullable=False),
    sa.Column('process_score', sa.Float(), nullable=False),
    sa.Column('quality_score', sa.Float(), nullable=False),
    sa.Column('feedback_json', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('ai_model_used', sa.String(length=255), nullable=False),
    sa.Column('assessed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['session_id'], ['interview_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('plan_tasks',
    sa.Column('daily_plan_id', sa.UUID(), nullable=False),
    sa.Column('type', sa.Enum('LEARN', 'PRACTICE', 'PROJECT', 'REVIEW', 'REST', name='tasktype'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('resource_url', sa.String(length=1024), nullable=True),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['daily_plan_id'], ['daily_plans.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmaps',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('career_goal_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('total_phases', sa.Integer(), nullable=False),
    sa.Column('current_phase', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Float(), nullable=False),
    sa.Column('ai_generated', sa.Boolean(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['career_goal_id'], ['career_goals.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('roadmap_phases',
    sa.Column('roadmap_id', sa.UUID(), nullable=False),
    sa.Column('phase_number', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('duration_weeks', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['roadmap_id'], ['roadmaps.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('milestones',
    sa.Column('phase_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('skills', postgresql.JSON(astext_type=sa.Text()), nullable=False),
    sa.Column('estimated_days', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'PAUSED', 'COMPLETED', name='status'), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['phase_id'], ['roadmap_phases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('milestones')
    op.drop_table('roadmap_phases')
    op.drop_table('roadmaps')
    op.drop_table('plan_tasks')
    op.drop_table('interview_assessments')
    op.drop_table('user_profiles')
    op.drop_table('user_preferences')
    op.drop_table('resumes')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('practice_sessions')
    op.drop_table('portfolio_projects')
    op.drop_table('leetcode_stats')
    op.drop_table('job_applications')
    op.drop_table('interview_sessions')
    op.drop_table('interview_prep')
    op.drop_table('github_profiles')
    op.drop_table('daily_plans')
    op.drop_table('career_goals')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('coding_problems')
    # ### end Alembic commands ###
